Improve the uninstall script  * The uninstall script now works on Fedora, Mandriva,...  * The uninstall script can now remove the l10n files

diff --git a/current/install b/current/install
--- a/current/install
+++ b/current/install
@@ -28,7 +28,7 @@
 ##                                                                        ##
 ############################################################################
 ##                                                                        ##
-## VERSION : 0.7 (Sat, 02 Jan 2010 22:47:34 +0100)                        ##
+## VERSION : 0.7 (Sun, 31 Jan 2010 20:23:45 +0100)                        ##
 ## WEB SITE : http://software.flogisoft.com/cover-thumbnailer/            ##
 ##                                                                       ##
 #########################################################################
@@ -37,7 +37,7 @@
 ##                                                                       ##
 ## ARGS :                                                                 ##
 ##   -p <path>                                                            ##
-##     Install path (default : /). Usefull for packaging                  ##
+##     Install path (default : /). Useful for packaging                   ##
 ##     NOTE : <path> with no "/" at the end !                             ##
  ##                                                                       ##
    #########################################################################
@@ -202,7 +202,8 @@ uninstall_ct() {
 	error=0
 
 	#gconf
-	gconf-schemas --unregister /usr/share/cover-thumbnailer/cover-thumbnailer.schema || error=1
+	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
+	gconftool-2 --makefile-uninstall-rule cover-thumbnailer.schema || error=1
 
 	#/usr/share/cover-thumbnailer
 	rm -rfv /usr/share/cover-thumbnailer || error=1
@@ -211,9 +212,11 @@ uninstall_ct() {
 	rm -vf /usr/share/man/man1/cover-thumbnailer.1.gz || error=1
 	rm -vf /usr/share/man/man1/cover-thumbnailer-gui.1.gz
 
-	#/usr/share/locale/xx_XX/LC_MESSAGES
-	#fr
-	rm -vf /usr/share/locale/fr/LC_MESSAGES/cover-thumbnailer-gui.mo
+	#/usr/share/locale/xx_XX/LC_MESSAGES/cover-thumbnailer-gui.mo
+	find /usr/share/locale/ \
+		-name cover-thumbnailer-gui.mo \
+		-exec rm -v '{}' ';' \
+		|| error=1
 
 	#/usr/bin
 	rm -vf /usr/bin/cover-thumbnailer || error=1
@@ -237,15 +240,20 @@ if [ `echo $LANG | head -c 2` == fr ] ; then {
 
 echo -e "$COLOR_INFO$LANG_INFOS_WELCOME$COLOR_DEFAULT"
 
-root ?
+#root ?
 if [ `whoami` != root ] ; then {
 	echo -e "$COLOR_ERROR$LANG_ERROR_ROOT$COLOR_DEFAULT"
 	exit 1
 } fi
 
 #Install path
-if [ "$1" == "-p" ] && [ -d "$2" ] ; then {
-	INSTP="$2"
+if [ "$1" == "-p" ] ; then {
+	if [ -d "$2" ] ; then {
+		INSTP="$2"
+	} else {
+		echo -e "${COLOR_ERROR}ERROR : folder '$2' not found !$COLOR_DEFAULT"
+		exit 2
+	} fi
 } fi
 
 #We go to the scrip directory
